on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

name: 01-python-script

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip requests

      - name: Execute Script
        run: |
          python "script.py"
